// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/nuea/todo-golang/cmd/todo-golang-api/internal"
	"github.com/nuea/todo-golang/internal/config"
)

// Injectors from di.go:

func InitializeContainer(cfg *config.AppConfig) (*Container, error) {
	server := internal.ProvideServer(cfg)
	container := &Container{
		cfg:    cfg,
		server: server,
	}
	return container, nil
}

// di.go:

type Container struct {
	cfg    *config.AppConfig
	server *internal.Server
}

func (c *Container) Run() {
	c.server.Run()
}

var ContainerSet = wire.NewSet(internal.ProvideServer)

var MainSet = wire.NewSet(
	ContainerSet, wire.Struct(new(Container), "*"),
)
